name: Deno CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Tests
        run: deno test --allow-net
  release:
    permissions: write-all
    name: Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip-release') && !contains(github.event.head_commit.message, 'skip-ci') && github.event_name != 'pull_request'"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
#      - name: Setup package.json
#        run: echo '{"name":"@0nza1101/heroku-awakener","version":"0.0.0","publishConfig":{"access":"public"},"scripts":{"semantic-release":"semantic-release"},"repository":{"type":"git","url":"https://github.com/0nza1101/heroku-awakener.git"},"author":"0nza1101<contact@jordan-nijean.com>","license":"MIT","bugs":{"url":"https://github.com/0nza1101/heroku-awakener/issues"},"homepage":"https://github.com/0nza1101/heroku-awakener","devDependencies":{"semantic-release":"^17.0.4","semantic-release-gitmoji":"^1.3.3"}}' > package.json
#      - name: Install dependencies
#        run: npm install
      - name: Release
        run: npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
